name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install packages
        run: composer install
      - name: Run PHPlint
        run: composer lint
      - name: Boot Laravel app
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run PHPunit
        run: composer test
